#!/bin/usr/env Rscript

#Setup
BiocManager::install("genomicsclass/maPooling")
library(Biobase)
library(maPooling)
data(maPooling)
pd=pData(maPooling)
pooled=which(rowSums(pd)==12)
individuals=which(rowSums(pd)==1)
##remove replicates
individuals=individuals[-grep("tr",names(individuals))]
pool = exprs(maPooling)[,pooled] 
indiv = exprs(maPooling)[,individuals]
strain = ifelse(grepl("a",rownames(pData(maPooling))),0,1)

g_pool = strain[pooled]
g_indiv = strain[individuals]


#For what proportion of genes is the estimated biological variability larger than the estimated technical variability?
library(genefilter)
tech = rowSds(pool[,g_pool==1])
bio = rowSds(indiv[,g_indiv==1])
mean(bio>tech)
## we can also make a plot
plot(tech,bio)
abline(0,1,col=2)

# Two Sample Tests, genome-wide, with FDR How many genes have q-values < 0.05 ?
library(genefilter)
library(qvalue)
pvals = rowttests(pool,factor(g_pool))$p.value
qvals = qvalue(pvals)$qvalue
sum(qvals < 0.05)

#For what proportion of these genes do we achieve the p-value from the biological replicates above 0.05?
library(genefilter)
library(qvalue)
pvals = rowttests(pool,factor(g_pool))$p.value
qvals = qvalue(pvals)$qvalue
ind = which(qvals<0.05)

pvals2 = rowttests(indiv,factor(g_indiv))$p.value
mean(pvals2[ind]>=0.05)

#What proportion of the genes with q-value < 0.05 obtained using t-tests have q-values < 0.05 when using the moderated t-test?
library(genefilter)
library(qvalue)
pvals = rowttests(indiv,factor(g_indiv))$p.value
qvals = qvalue(pvals)$qvalue
library(limma)
X = model.matrix(~g_indiv)
fit = lmFit(indiv,X)
eb = eBayes(fit)
pvals2= eb$p.value[,2]
qvals2= qvalue(pvals2)$qvalue
sum( qvals2<0.05 & qvals<0.05)/sum(qvals<0.05)



